# Generated by Django 5.0.4 on 2024-08-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('AvgGrade', models.IntegerField()),
                ('AvgCet', models.IntegerField()),
                ('TotalScore', models.IntegerField()),
                ('CourseDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Feedback', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvgGrade', models.IntegerField()),
                ('AvgCet', models.IntegerField()),
                ('TotalScore', models.IntegerField()),
                ('BSLaws', models.IntegerField()),
                ('BSAgriculture', models.IntegerField()),
                ('BSAgribusiness', models.IntegerField()),
                ('BSAgricultureTechnology', models.IntegerField()),
                ('BSArchitecture', models.IntegerField()),
                ('BSNursing', models.IntegerField()),
                ('BSInformationTechnology', models.IntegerField()),
                ('BSComputerScience', models.IntegerField()),
                ('AComputerTechnology', models.IntegerField()),
                ('BSForestry', models.IntegerField()),
                ('BSAgroforestry', models.IntegerField()),
                ('BSEnvironmentScience', models.IntegerField()),
                ('BSAccountancy', models.IntegerField()),
                ('BAHistory', models.IntegerField()),
                ('BAEnglish', models.IntegerField()),
                ('BAPoliticalScience', models.IntegerField()),
                ('BAMCJournalism', models.IntegerField()),
                ('BAMCBroadcasting', models.IntegerField()),
                ('BSEconomics', models.IntegerField()),
                ('BSPsycology', models.IntegerField()),
                ('BSNutritionandDietetics', models.IntegerField()),
                ('BSHomeEconomics', models.IntegerField()),
                ('BSFoodTechnology', models.IntegerField()),
                ('BSAgriculturalandBiosystemsEngineering', models.IntegerField()),
                ('BSCivilEngineering', models.IntegerField()),
                ('BSComputerEngineering', models.IntegerField()),
                ('BSElectricalEngineering', models.IntegerField()),
                ('BSElectronicsEngineering', models.IntegerField()),
                ('BSEnvironmentalEngineering', models.IntegerField()),
                ('BSGeodeticEngineering', models.IntegerField()),
                ('BSIndustrialEngineering', models.IntegerField()),
                ('BSMechanicalEngineering', models.IntegerField()),
                ('BSSanitaryEngineering', models.IntegerField()),
                ('BSPublicAdministration', models.IntegerField()),
                ('BSPhysicalEducatio', models.IntegerField()),
                ('BSExerciseandSportScience', models.IntegerField()),
                ('BSSocialWork', models.IntegerField()),
                ('BSCommunityDevelopment', models.IntegerField()),
                ('BCultureandArtsEducation', models.IntegerField()),
                ('BEarlyChildhoodEducation', models.IntegerField()),
                ('BElementaryEducation', models.IntegerField()),
                ('BSecondaryEducation', models.IntegerField()),
                ('BSpecialNeedsEducation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('AvgGrade', models.IntegerField()),
                ('AvgCet', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('courseName', models.CharField(default='General', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('response', models.IntegerField()),
                ('courseName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
