# Generated by Django 5.1 on 2024-08-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0004_remove_grades_bcultureandartseducation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='StudentID',
            field=models.IntegerField(default=0),
        ),
    ]
