# Generated by Django 5.1 on 2024-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0006_remove_grades_acomputertechnology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='TotalScore',
        ),
        migrations.AddField(
            model_name='grades',
            name='PersonalityScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='courseName',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
