# Generated by Django 5.1 on 2024-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0007_remove_grades_totalscore_grades_personalityscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='TotalScore',
            field=models.IntegerField(default=0),
        ),
    ]
