# Generated by Django 5.1 on 2024-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0008_grades_totalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='AvgCet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='AvgGrade',
            field=models.IntegerField(default=0),
        ),
    ]
