# Generated by Django 5.1 on 2024-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0010_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
