# Generated by Django 5.1 on 2024-09-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0013_admin_course_admin_designation_admin_name_admin_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
