# Generated by Django 5.1 on 2024-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0015_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
