# Generated by Django 5.1 on 2024-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0017_list_applicationno'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Address',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='admin',
            name='College',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='admin',
            name='Number',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='list',
            name='ApplicationNo',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
