# Generated by Django 5.1 on 2024-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0018_admin_address_admin_college_admin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
