# Generated by Django 5.1 on 2024-10-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0020_alter_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Percentage',
            field=models.IntegerField(default=0),
        ),
    ]
