# Generated by Django 5.1 on 2024-10-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0022_grades_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='Percentage',
        ),
    ]
