# Generated by Django 5.1 on 2024-10-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0024_alter_question_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
