# Generated by Django 5.0.4 on 2024-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0025_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Logo',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
