# Generated by Django 5.0.4 on 2024-11-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0028_alter_otp_created_at_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='AvgCet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='AvgGrade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='TotalScore',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='AvgCet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='AvgGrade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='PersonalityScore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='StudentID',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='TotalScore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='Percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='AvgCet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='AvgGrade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='StudentID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='response',
            field=models.FloatField(),
        ),
    ]
