# Generated by Django 5.0.4 on 2024-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0029_alter_course_avgcet_alter_course_avggrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Course',
            field=models.CharField(default='null', max_length=255, unique=True),
        ),
    ]
