# Generated by Django 5.0.4 on 2024-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0030_alter_admin_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
