# Generated by Django 5.0.4 on 2024-11-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0031_question_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='reason',
        ),
    ]
