# Generated by Django 5.0.4 on 2024-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0032_remove_question_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
