# Generated by Django 5.0.4 on 2024-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0033_course_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Year',
            field=models.IntegerField(default=0),
        ),
    ]
