# Generated by Django 5.0.4 on 2024-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0034_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Year',
            field=models.IntegerField(default=0),
        ),
    ]
