# Generated by Django 5.0.4 on 2024-11-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0035_list_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CetAvgPercentage', models.FloatField(default=0)),
                ('GradeAvgPercentage', models.FloatField(default=0)),
                ('PersonalityPercentage', models.FloatField(default=0)),
            ],
        ),
    ]
